"""Gemini CLI adapter — `.gemini/commands/<name>.toml`.

Gemini CLI uses flat TOML commands rather than skill directories, so this adapter
does a genuine format translation (research.md R1):

* YAML frontmatter + Markdown body -> ``description`` + ``prompt`` TOML keys
* ``$ARGUMENTS`` -> ``{{args}}`` (Gemini's placeholder)

The payload (prompts, schemas, scripts) still installs into a sibling directory so
the command body can reference it.

Docs: https://google-gemini.github.io/gemini-cli/docs/cli/custom-commands.html
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from installer.agents.base import Adapter, split_frontmatter


def _toml_escape_basic(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip()


def _toml_multiline(value: str) -> str:
    """Render a TOML multi-line basic string safely."""
    body = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    # A trailing quote would terminate the delimiter ambiguously.
    if body.endswith('"'):
        body += "\\"
    return f'"""\n{body}\n"""'


class GeminiAdapter(Adapter):
    key = "gemini"
    label = "Gemini CLI"
    #: Gemini keeps commands flat; the payload lives beside them.
    skills_subdir = (".gemini", "commands")
    invocation = "/{name}"

    def skill_dir(self, project_root: Path, name: str) -> Path:
        # Payload directory (sibling of the flat command file).
        return self.skills_dir(project_root) / name

    def entrypoint(self, project_root: Path, name: str) -> Path:
        return self.skills_dir(project_root) / f"{name}.toml"

    def render_entrypoint(self, core_text: str, name: str) -> str:
        front, body = split_frontmatter(core_text)
        description = _toml_escape_basic(str(front.get("description", "")))
        prompt = body.replace("$ARGUMENTS", "{{args}}")
        lines = [
            f"# {name} - generated by secscan; edit the installed SKILL.md instead.",
            f'description = "{description}"',
            f"prompt = {_toml_multiline(prompt)}",
        ]
        return "\n".join(lines) + "\n"

    def parse_entrypoint(self, path: Path) -> dict[str, Any]:
        text = Path(path).read_text()
        description = ""
        for line in text.splitlines():
            if line.startswith("description = "):
                description = line.split("=", 1)[1].strip().strip('"')
                break
        start = text.find('prompt = """')
        body = ""
        if start != -1:
            body = text[start + len('prompt = """') :]
            end = body.rfind('"""')
            if end != -1:
                body = body[:end]
        return {
            "name": path.stem,
            "description": description,
            "frontmatter": {"description": description},
            "body": body.strip(),
        }
